export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const PERSIST_REHYDRATE = 'persist/REHYDRATE';

export const LIST_DRIVER_REQUEST = 'LIST_DRIVER_REQUEST';
export const LIST_DRIVER_SUCCESS = 'LIST_DRIVER_SUCCESS';
export const LIST_DRIVER_FAILURE = 'LIST_DRIVER_FAILURE';
export const ADD_DRIVER_REQUEST = 'ADD_DRIVER_REQUEST';
export const ADD_DRIVER_SUCCESS = 'ADD_DRIVER_SUCCESS';
export const ADD_DRIVER_FAILURE = 'ADD_DRIVER_FAILURE';
export const DELETE_DRIVER_REQUEST = 'DELETE_DRIVER_REQUEST';
export const DELETE_DRIVER_SUCCESS = 'DELETE_DRIVER_SUCCESS';
export const DELETE_DRIVER_FAILURE = 'DELETE_DRIVER_FAILURE';

export const LIST_TRAVEL_REQUEST = 'LIST_TRAVEL_REQUEST';
export const LIST_TRAVEL_SUCCESS = 'LIST_TRAVEL_SUCCESS';
export const LIST_TRAVEL_FAILURE = 'LIST_TRAVEL_FAILURE';
export const ADD_TRAVEL_REQUEST = 'ADD_TRAVEL_REQUEST';
export const ADD_TRAVEL_SUCCESS = 'ADD_TRAVEL_SUCCESS';
export const ADD_TRAVEL_FAILURE = 'ADD_TRAVEL_FAILURE';
export const DELETE_TRAVEL_REQUEST = 'DELETE_TRAVEL_REQUEST';
export const DELETE_TRAVEL_SUCCESS = 'DELETE_TRAVEL_SUCCESS';
export const DELETE_TRAVEL_FAILURE = 'DELETE_TRAVEL_FAILURE';

export const SELECTED_DRIVER = 'SELECTED_DRIVER';
export const SHOW_DRIVER = 'SHOW_DRIVER';

export const PAGE_ACTIVE = 'PAGE_ACTIVE';
export const STATUS_MODAL = 'STATUS_MODAL';
